package com.google.android.gms.measurement.internal;

import android.content.Context;
import androidx.annotation.Nullable;
import com.google.android.gms.common.util.VisibleForTesting;
import com.google.firebase.firestore.util.ExponentialBackoff;
import com.google.logging.type.LogSeverity;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

@VisibleForTesting
/* loaded from: classes.dex */
public final class zzap {
    public static zzel<Long> zzaa;
    public static zzel<Long> zzab;
    public static zzel<Integer> zzac;
    public static zzel<Long> zzad;
    public static zzel<Integer> zzae;
    public static zzel<Integer> zzaf;
    public static zzel<Long> zzag;
    public static zzel<Boolean> zzah;
    public static zzel<String> zzai;
    public static zzel<Long> zzaj;
    public static zzel<Integer> zzak;
    public static zzel<Double> zzal;
    public static zzel<Integer> zzam;
    public static zzel<Boolean> zzan;
    public static zzel<Boolean> zzao;
    public static zzel<Boolean> zzap;
    public static zzel<Boolean> zzaq;
    public static zzel<Boolean> zzar;
    public static zzel<Boolean> zzas;
    public static zzel<Boolean> zzat;
    public static zzel<Boolean> zzau;
    public static zzel<Boolean> zzav;
    public static zzel<Boolean> zzaw;
    public static zzel<Boolean> zzax;
    public static zzel<Boolean> zzay;
    public static zzel<Boolean> zzaz;
    public static zzel<Boolean> zzba;
    public static zzel<Boolean> zzbb;
    public static zzel<Boolean> zzbc;
    public static zzel<Boolean> zzbd;
    public static zzel<Boolean> zzbe;
    public static zzel<Boolean> zzbf;
    public static zzel<Boolean> zzbg;
    public static zzel<Boolean> zzbh;
    public static zzel<Boolean> zzbi;
    public static zzel<Boolean> zzbj;
    public static zzel<Boolean> zzbk;
    public static zzel<Boolean> zzbl;
    public static zzel<Boolean> zzbm;
    public static zzel<Boolean> zzbn;
    public static zzel<Boolean> zzbo;
    public static zzel<Boolean> zzbp;
    public static zzel<Boolean> zzbq;
    public static zzel<Boolean> zzbr;
    public static zzel<Boolean> zzbs;
    public static zzel<Boolean> zzbt;
    public static zzel<Boolean> zzbu;
    public static zzel<Boolean> zzbv;
    public static zzel<Boolean> zzbw;
    public static zzel<Boolean> zzbx;
    public static zzel<Boolean> zzby;
    public static zzel<Boolean> zzbz;
    public static zzel<Boolean> zzca;
    public static zzel<Boolean> zzcb;
    public static zzel<Boolean> zzcc;
    public static zzel<Boolean> zzcd;
    public static zzel<Boolean> zzce;
    public static zzel<Boolean> zzcf;
    public static zzel<Boolean> zzcg;
    public static zzel<Boolean> zzch;
    public static zzel<Boolean> zzci;
    public static zzel<Boolean> zzcj;
    public static zzel<Boolean> zzck;
    public static zzel<Boolean> zzcl;
    public static zzel<Boolean> zzcm;
    public static zzel<Boolean> zzcn;
    public static zzel<Boolean> zzco;
    public static zzel<Boolean> zzcp;
    public static zzel<Boolean> zzcq;
    private static zzel<Boolean> zzct;
    private static zzel<Boolean> zzcu;
    public static zzel<Integer> zzn;
    public static zzel<Integer> zzo;
    public static zzel<Integer> zzp;
    public static zzel<String> zzq;
    public static zzel<Long> zzr;
    public static zzel<Long> zzs;
    public static zzel<Long> zzt;
    public static zzel<Long> zzu;
    public static zzel<Long> zzv;
    public static zzel<Long> zzw;
    public static zzel<Long> zzx;
    public static zzel<Long> zzy;
    public static zzel<Long> zzz;
    private static List<zzel<?>> zzcr = Collections.synchronizedList(new ArrayList());
    private static Set<zzel<?>> zzcs = Collections.synchronizedSet(new HashSet());
    public static zzel<Boolean> zza = zza("measurement.upload_dsid_enabled", true, true, zzas.a);
    public static zzel<Long> zzb = zza("measurement.ad_id_cache_time", 10000L, 10000L, zzar.a);
    public static zzel<Long> zzc = zza("measurement.monitoring.sample_period_millis", 86400000L, 86400000L, zzbe.a);
    public static zzel<Long> zzd = zza("measurement.config.cache_time", 86400000L, 3600000L, zzbn.a);
    public static zzel<String> zze = zza("measurement.config.url_scheme", "https", "https", zzca.a);
    public static zzel<String> zzf = zza("measurement.config.url_authority", "app-measurement.com", "app-measurement.com", zzcj.a);
    public static zzel<Integer> zzg = zza("measurement.upload.max_bundles", 100, 100, zzcw.a);
    public static zzel<Integer> zzh = zza("measurement.upload.max_batch_size", 65536, 65536, zzdf.a);
    public static zzel<Integer> zzi = zza("measurement.upload.max_bundle_size", 65536, 65536, zzds.a);
    public static zzel<Integer> zzj = zza("measurement.upload.max_events_per_bundle", 1000, 1000, zzeb.a);
    public static zzel<Integer> zzk = zza("measurement.upload.max_events_per_day", 100000, 100000, zzau.a);
    public static zzel<Integer> zzl = zza("measurement.upload.max_error_events_per_day", 1000, 1000, zzat.a);
    public static zzel<Integer> zzm = zza("measurement.upload.max_public_events_per_day", 50000, 50000, zzaw.a);

    static {
        Integer valueOf = Integer.valueOf(LogSeverity.ERROR_VALUE);
        zzn = zza("measurement.upload.max_conversions_per_day", valueOf, valueOf, zzav.a);
        zzo = zza("measurement.upload.max_realtime_events_per_day", 10, 10, zzay.a);
        zzp = zza("measurement.store.max_stored_events_per_app", 100000, 100000, zzax.a);
        zzq = zza("measurement.upload.url", "https://app-measurement.com/a", "https://app-measurement.com/a", zzba.a);
        zzr = zza("measurement.upload.backoff_period", 43200000L, 43200000L, zzaz.a);
        zzs = zza("measurement.upload.window_interval", 3600000L, 3600000L, zzbc.a);
        zzt = zza("measurement.upload.interval", 3600000L, 3600000L, zzbb.a);
        zzu = zza("measurement.upload.realtime_upload_interval", 10000L, 10000L, zzbd.a);
        zzv = zza("measurement.upload.debug_upload_interval", 1000L, 1000L, zzbg.a);
        zzw = zza("measurement.upload.minimum_delay", 500L, 500L, zzbf.a);
        Long valueOf2 = Long.valueOf(ExponentialBackoff.DEFAULT_BACKOFF_MAX_DELAY_MS);
        zzx = zza("measurement.alarm_manager.minimum_interval", valueOf2, valueOf2, zzbi.a);
        zzy = zza("measurement.upload.stale_data_deletion_interval", 86400000L, 86400000L, zzbh.a);
        zzz = zza("measurement.upload.refresh_blacklisted_config_interval", 604800000L, 604800000L, zzbk.a);
        zzaa = zza("measurement.upload.initial_upload_delay_time", 15000L, 15000L, zzbj.a);
        zzab = zza("measurement.upload.retry_time", 1800000L, 1800000L, zzbm.a);
        zzac = zza("measurement.upload.retry_count", 6, 6, zzbl.a);
        zzad = zza("measurement.upload.max_queue_time", 2419200000L, 2419200000L, zzbo.a);
        zzae = zza("measurement.lifetimevalue.max_currency_tracked", 4, 4, zzbq.a);
        zzaf = zza("measurement.audience.filter_result_max_count", 200, 200, zzbp.a);
        zzag = zza("measurement.service_client.idle_disconnect_millis", 5000L, 5000L, zzbs.a);
        zzah = zza("measurement.test.boolean_flag", false, false, zzbr.a);
        zzai = zza("measurement.test.string_flag", "---", "---", zzbu.a);
        zzaj = zza("measurement.test.long_flag", -1L, -1L, zzbt.a);
        zzak = zza("measurement.test.int_flag", -2, -2, zzbw.a);
        Double valueOf3 = Double.valueOf(-3.0d);
        zzal = zza("measurement.test.double_flag", valueOf3, valueOf3, zzbv.a);
        zzam = zza("measurement.experiment.max_ids", 50, 50, zzby.a);
        zzan = zza("measurement.validation.internal_limits_internal_event_params", false, false, zzbx.a);
        zzao = zza("measurement.referrer.enable_logging_install_referrer_cmp_from_apk", false, false, zzbz.a);
        zzap = zza("measurement.client.sessions.session_id_enabled", true, true, zzcc.a);
        zzaq = zza("measurement.service.sessions.session_number_enabled", true, true, zzcb.a);
        zzar = zza("measurement.client.sessions.background_sessions_enabled", true, true, zzce.a);
        zzas = zza("measurement.client.sessions.remove_expired_session_properties_enabled", true, true, zzcd.a);
        zzat = zza("measurement.service.sessions.session_number_backfill_enabled", true, true, zzcg.a);
        zzau = zza("measurement.service.sessions.remove_disabled_session_number", true, true, zzcf.a);
        zzav = zza("measurement.client.sessions.start_session_before_view_screen", true, true, zzci.a);
        zzaw = zza("measurement.client.sessions.check_on_startup", true, true, zzch.a);
        zzax = zza("measurement.collection.firebase_global_collection_flag_enabled", true, true, zzck.a);
        zzay = zza("measurement.collection.efficient_engagement_reporting_enabled", false, false, zzcm.a);
        zzaz = zza("measurement.collection.redundant_engagement_removal_enabled", false, false, zzcl.a);
        zzba = zza("measurement.personalized_ads_signals_collection_enabled", true, true, zzco.a);
        zzbb = zza("measurement.personalized_ads_property_translation_enabled", true, true, zzcn.a);
        zzbc = zza("measurement.upload.disable_is_uploader", true, true, zzcq.a);
        zzbd = zza("measurement.experiment.enable_experiment_reporting", true, true, zzcp.a);
        zzbe = zza("measurement.collection.log_event_and_bundle_v2", true, true, zzcs.a);
        zzbf = zza("measurement.quality.checksum", false, false, null);
        zzbg = zza("measurement.module.collection.conditionally_omit_admob_app_id", true, true, zzcr.a);
        zzbh = zza("measurement.sdk.dynamite.use_dynamite2", false, false, zzcu.a);
        zzbi = zza("measurement.sdk.dynamite.allow_remote_dynamite", false, false, zzct.a);
        zzbj = zza("measurement.sdk.collection.validate_param_names_alphabetical", false, false, zzcv.a);
        zzbk = zza("measurement.collection.event_safelist", true, true, zzcy.a);
        zzbl = zza("measurement.service.audience.scoped_filters_v27", false, false, zzcx.a);
        zzbm = zza("measurement.service.audience.session_scoped_event_aggregates", false, false, zzda.a);
        zzbn = zza("measurement.service.audience.session_scoped_user_engagement", false, false, zzcz.a);
        zzbo = zza("measurement.service.audience.scoped_engagement_removal_when_session_expired", true, true, zzdc.a);
        zzbp = zza("measurement.client.audience.scoped_engagement_removal_when_session_expired", true, true, zzdb.a);
        zzbq = zza("measurement.service.audience.remove_disabled_session_scoped_user_engagement", false, false, zzde.a);
        zzbr = zza("measurement.service.audience.use_bundle_timestamp_for_property_filters", false, false, zzdd.a);
        zzbs = zza("measurement.service.audience.fix_prepending_previous_sequence_timestamp", false, false, zzdg.a);
        zzct = zza("measurement.service.audience.invalidate_config_cache_after_app_unisntall", false, false, zzdi.a);
        zzbt = zza("measurement.service.audience.fix_skip_audience_with_failed_filters", true, true, zzdh.a);
        zzbu = zza("measurement.sdk.collection.retrieve_deeplink_from_bow_2", true, true, zzdk.a);
        zzbv = zza("measurement.app_launch.event_ordering_fix", false, false, zzdj.a);
        zzbw = zza("measurement.sdk.collection.last_deep_link_referrer", false, false, zzdm.a);
        zzbx = zza("measurement.sdk.collection.last_deep_link_referrer_campaign", false, false, zzdl.a);
        zzby = zza("measurement.sdk.collection.last_gclid_from_referrer", false, false, zzdo.a);
        zzbz = zza("measurement.sdk.collection.worker_thread_referrer", true, true, zzdn.a);
        zzca = zza("measurement.upload.file_lock_state_check", false, false, zzdq.a);
        zzcb = zza("measurement.sampling.calculate_bundle_timestamp_before_sampling", true, true, zzdp.a);
        zzcc = zza("measurement.ga.ga_app_id", false, false, zzdr.a);
        zzcd = zza("measurement.lifecycle.app_backgrounded_tracking", false, false, zzdu.a);
        zzce = zza("measurement.lifecycle.app_in_background_parameter", false, false, zzdt.a);
        zzcf = zza("measurement.integration.disable_firebase_instance_id", false, false, zzdw.a);
        zzcg = zza("measurement.lifecycle.app_backgrounded_engagement", false, false, zzdv.a);
        zzch = zza("measurement.service.fix_gmp_version", false, false, zzdy.a);
        zzci = zza("measurement.collection.service.update_with_analytics_fix", false, false, zzdx.a);
        zzcj = zza("measurement.service.disable_install_state_reporting", false, false, zzea.a);
        zzck = zza("measurement.service.use_appinfo_modified", false, false, zzdz.a);
        zzcu = zza("measurement.upload.dsid_reflection_failure_logging", true, true, zzec.a);
        zzcl = zza("measurement.client.firebase_feature_rollout.v1.enable", true, true, zzee.a);
        zzcm = zza("measurement.client.sessions.check_on_reset_and_enable", false, false, zzed.a);
        zzcn = zza("measurement.config.string.always_update_disk_on_set", false, false, zzeg.a);
        zzco = zza("measurement.scheduler.task_thread.cleanup_on_exit", false, false, zzef.a);
        zzcp = zza("measurement.upload.file_truncate_fix", false, false, zzei.a);
        zzcq = zza("measurement.lifecycle.app_background_timestamp_when_backgrounded", true, true, zzeh.a);
    }

    public static final /* synthetic */ Long r0() {
        zzw zzwVar = zzem.a;
        return Long.valueOf(com.google.android.gms.internal.measurement.zzjd.zzc());
    }

    @VisibleForTesting
    private static <V> zzel<V> zza(@Nullable String str, @Nullable V v, @Nullable V v2, @Nullable zzej<V> zzejVar) {
        zzel<V> zzelVar = new zzel<>(str, v, v2, zzejVar);
        zzcr.add(zzelVar);
        return zzelVar;
    }

    public static Map<String, String> zza(Context context) {
        com.google.android.gms.internal.measurement.zzbx zza2 = com.google.android.gms.internal.measurement.zzbx.zza(context.getContentResolver(), com.google.android.gms.internal.measurement.zzcm.zza("com.google.android.gms.measurement"));
        return zza2 == null ? Collections.emptyMap() : zza2.zza();
    }
}
