package x6;

/* loaded from: classes.dex */
public enum e {
    OK,
    FILE_ALREADY_EXIST,
    NO_STOP_ACTION_AVAILABLE,
    FILE_PLAYING,
    FILE_RECORDING,
    FILE_NOT_EXIST,
    SYSTEM_EXCEPTION,
    NO_PAUSE_ACTION_AVAILABLE,
    FILE_DOWNLOADING,
    FILE_UPLOADING,
    NO_SERVER_PATH,
    NO_UPLOAD_HANDLER,
    ERROR_READING_FILE,
    ERROR_UPLOADING
}
