package L0;

/* loaded from: classes.dex */
public enum e {
    JAR_SIG_NO_SIGNATURES("No JAR signatures"),
    JAR_SIG_MAX_SIGNATURES_EXCEEDED("APK Signature Scheme v1 only supports a maximum of %1$d signers, found %2$d"),
    JAR_SIG_NO_SIGNED_ZIP_ENTRIES("No JAR entries covered by JAR signatures"),
    JAR_SIG_DUPLICATE_ZIP_ENTRY("Duplicate entry: %1$s"),
    JAR_SIG_DUPLICATE_MANIFEST_SECTION("Duplicate section in META-INF/MANIFEST.MF: %1$s"),
    JAR_SIG_UNNNAMED_MANIFEST_SECTION("Malformed META-INF/MANIFEST.MF: invidual section #%1$d does not have a name"),
    JAR_SIG_UNNNAMED_SIG_FILE_SECTION("Malformed %1$s: invidual section #%2$d does not have a name"),
    JAR_SIG_NO_MANIFEST("Missing META-INF/MANIFEST.MF"),
    JAR_SIG_MISSING_ZIP_ENTRY_REFERENCED_IN_MANIFEST("%1$s entry referenced by META-INF/MANIFEST.MF not found in the APK"),
    JAR_SIG_NO_ZIP_ENTRY_DIGEST_IN_MANIFEST("No digest for %1$s in META-INF/MANIFEST.MF"),
    JAR_SIG_NO_ZIP_ENTRY_DIGEST_IN_SIG_FILE("No digest for %1$s in %2$s"),
    JAR_SIG_ZIP_ENTRY_NOT_SIGNED("%1$s entry not signed"),
    JAR_SIG_ZIP_ENTRY_SIGNERS_MISMATCH("Entries %1$s and %3$s are signed with different sets of signers : <%2$s> vs <%4$s>"),
    JAR_SIG_ZIP_ENTRY_DIGEST_DID_NOT_VERIFY("%2$s digest of %1$s does not match the digest specified in %3$s. Expected: <%5$s>, actual: <%4$s>"),
    JAR_SIG_MANIFEST_MAIN_SECTION_DIGEST_DID_NOT_VERIFY("%1$s digest of META-INF/MANIFEST.MF main section does not match the digest specified in %2$s. Expected: <%4$s>, actual: <%3$s>"),
    JAR_SIG_MANIFEST_SECTION_DIGEST_DID_NOT_VERIFY("%2$s digest of META-INF/MANIFEST.MF section for %1$s does not match the digest specified in %3$s. Expected: <%5$s>, actual: <%4$s>"),
    JAR_SIG_NO_MANIFEST_DIGEST_IN_SIG_FILE("%1$s does not specify digest of META-INF/MANIFEST.MF. This slows down verification."),
    JAR_SIG_NO_APK_SIG_STRIP_PROTECTION("APK is signed using APK Signature Scheme v2 but these signatures may be stripped without being detected because %1$s does not contain anti-stripping protections."),
    JAR_SIG_MISSING_FILE("Partial JAR signature. Found: %1$s, missing: %2$s"),
    JAR_SIG_VERIFY_EXCEPTION("Failed to verify JAR signature %1$s against %2$s: %3$s"),
    JAR_SIG_UNSUPPORTED_SIG_ALG("JAR signature %1$s uses digest algorithm %5$s and signature algorithm %6$s which is not supported on API Level(s) %4$s for which this APK is being verified"),
    JAR_SIG_PARSE_EXCEPTION("Failed to parse JAR signature %1$s: %2$s"),
    /* JADX INFO: Fake field, exist only in values array */
    JAR_SIG_MALFORMED_CERTIFICATE("Malformed certificate in JAR signature %1$s: %2$s"),
    JAR_SIG_DID_NOT_VERIFY("JAR signature %1$s did not verify against %2$s"),
    JAR_SIG_NO_SIGNERS("JAR signature %1$s contains no signers"),
    JAR_SIG_DUPLICATE_SIG_FILE_SECTION("Duplicate section in %1$s: %2$s"),
    JAR_SIG_MISSING_VERSION_ATTR_IN_SIG_FILE("Malformed %1$s: missing Signature-Version attribute"),
    JAR_SIG_UNKNOWN_APK_SIG_SCHEME_ID("JAR signature %1$s references unknown APK signature scheme ID: %2$d"),
    JAR_SIG_MISSING_APK_SIG_REFERENCED("JAR signature %1$s indicates the APK is signed using %3$s but no such signature was found. Signature stripped?"),
    JAR_SIG_UNPROTECTED_ZIP_ENTRY("%1$s not protected by signature. Unauthorized modifications to this JAR entry will not be detected. Delete or move the entry outside of META-INF/."),
    JAR_SIG_MISSING("No JAR signature from this signer"),
    NO_SIG_FOR_TARGET_SANDBOX_VERSION("Missing APK Signature Scheme v2 signature required for target sandbox version %1$d"),
    MIN_SIG_SCHEME_FOR_TARGET_SDK_NOT_MET("Target SDK version %1$d requires a minimum of signature scheme v%2$d; the APK is not signed with this or a later signature scheme"),
    V2_SIG_MISSING("No APK Signature Scheme v2 signature from this signer"),
    V2_SIG_MALFORMED_SIGNERS("Malformed list of signers"),
    V2_SIG_MALFORMED_SIGNER("Malformed signer block"),
    V2_SIG_MALFORMED_PUBLIC_KEY("Malformed public key: %1$s"),
    V2_SIG_MALFORMED_CERTIFICATE("Malformed certificate #%2$d: %3$s"),
    V2_SIG_MALFORMED_SIGNATURE("Malformed APK Signature Scheme v2 signature record #%1$d"),
    V2_SIG_MALFORMED_DIGEST("Malformed APK Signature Scheme v2 digest record #%1$d"),
    V2_SIG_MALFORMED_ADDITIONAL_ATTRIBUTE("Malformed additional attribute #%1$d"),
    V2_SIG_UNKNOWN_APK_SIG_SCHEME_ID("APK Signature Scheme v2 signer: %1$s references unknown APK signature scheme ID: %2$d"),
    V2_SIG_MISSING_APK_SIG_REFERENCED("APK Signature Scheme v2 signature %1$s indicates the APK is signed using %2$s but no such signature was found. Signature stripped?"),
    V2_SIG_MAX_SIGNATURES_EXCEEDED("APK Signature Scheme V2 only supports a maximum of %1$d signers, found %2$d"),
    V2_SIG_NO_SIGNERS("No signers in APK Signature Scheme v2 signature"),
    V2_SIG_UNKNOWN_SIG_ALGORITHM("Unknown signature algorithm: %1$#x"),
    V2_SIG_UNKNOWN_ADDITIONAL_ATTRIBUTE("Unknown additional attribute: ID %1$#x"),
    V2_SIG_VERIFY_EXCEPTION("Failed to verify %1$s signature: %2$s"),
    V2_SIG_DID_NOT_VERIFY("%1$s signature over signed-data did not verify"),
    V2_SIG_NO_SIGNATURES("No signatures"),
    V2_SIG_NO_SUPPORTED_SIGNATURES("No supported signatures: %1$s"),
    V2_SIG_NO_CERTIFICATES("No certificates"),
    V2_SIG_PUBLIC_KEY_MISMATCH_BETWEEN_CERTIFICATE_AND_SIGNATURES_RECORD("Public key mismatch between certificate and signature record: <%1$s> vs <%2$s>"),
    V2_SIG_SIG_ALG_MISMATCH_BETWEEN_SIGNATURES_AND_DIGESTS_RECORDS("Signature algorithms mismatch between signatures and digests records: %1$s vs %2$s"),
    V2_SIG_APK_DIGEST_DID_NOT_VERIFY("APK integrity check failed. %1$s digest mismatch. Expected: <%2$s>, actual: <%3$s>"),
    V3_SIG_MALFORMED_SIGNERS("Malformed list of signers"),
    V3_SIG_MALFORMED_SIGNER("Malformed signer block"),
    V3_SIG_MALFORMED_PUBLIC_KEY("Malformed public key: %1$s"),
    V3_SIG_MALFORMED_CERTIFICATE("Malformed certificate #%2$d: %3$s"),
    V3_SIG_MALFORMED_SIGNATURE("Malformed APK Signature Scheme v3 signature record #%1$d"),
    V3_SIG_MALFORMED_DIGEST("Malformed APK Signature Scheme v3 digest record #%1$d"),
    V3_SIG_MALFORMED_ADDITIONAL_ATTRIBUTE("Malformed additional attribute #%1$d"),
    V3_SIG_NO_SIGNERS("No signers in APK Signature Scheme v3 signature"),
    V3_SIG_MULTIPLE_SIGNERS("Multiple APK Signature Scheme v3 signatures found for a single  platform version."),
    V3_SIG_MULTIPLE_PAST_SIGNERS("Multiple signatures found for pre-v3 signing with an APK  Signature Scheme v3 signer.  Only one allowed."),
    V3_SIG_PAST_SIGNERS_MISMATCH("v3 signer differs from v1/v2 signer without proper signing certificate lineage."),
    V3_SIG_UNKNOWN_SIG_ALGORITHM("Unknown signature algorithm: %1$#x"),
    V3_SIG_UNKNOWN_ADDITIONAL_ATTRIBUTE("Unknown additional attribute: ID %1$#x"),
    V3_SIG_VERIFY_EXCEPTION("Failed to verify %1$s signature: %2$s"),
    V3_SIG_INVALID_SDK_VERSIONS("Invalid SDK Version parameter(s) encountered in APK Signature scheme v3 signature: minSdkVersion %1$s maxSdkVersion: %2$s"),
    V3_SIG_DID_NOT_VERIFY("%1$s signature over signed-data did not verify"),
    V3_SIG_NO_SIGNATURES("No signatures"),
    V3_SIG_NO_SUPPORTED_SIGNATURES("No supported signatures"),
    V3_SIG_NO_CERTIFICATES("No certificates"),
    V3_MIN_SDK_VERSION_MISMATCH_BETWEEN_SIGNER_AND_SIGNED_DATA_RECORD("minSdkVersion mismatch between signed data and signature record: <%1$s> vs <%2$s>"),
    V3_MAX_SDK_VERSION_MISMATCH_BETWEEN_SIGNER_AND_SIGNED_DATA_RECORD("maxSdkVersion mismatch between signed data and signature record: <%1$s> vs <%2$s>"),
    V3_SIG_PUBLIC_KEY_MISMATCH_BETWEEN_CERTIFICATE_AND_SIGNATURES_RECORD("Public key mismatch between certificate and signature record: <%1$s> vs <%2$s>"),
    V3_SIG_SIG_ALG_MISMATCH_BETWEEN_SIGNATURES_AND_DIGESTS_RECORDS("Signature algorithms mismatch between signatures and digests records: %1$s vs %2$s"),
    V3_SIG_APK_DIGEST_DID_NOT_VERIFY("APK integrity check failed. %1$s digest mismatch. Expected: <%2$s>, actual: <%3$s>"),
    V3_SIG_POR_DID_NOT_VERIFY("SigningCertificateLineage attribute containd a proof-of-rotation record with signature(s) that did not verify."),
    V3_SIG_MALFORMED_LINEAGE("Failed to parse the SigningCertificateLineage structure in the APK Signature Scheme v3 signature's additional attributes section."),
    V3_SIG_POR_CERT_MISMATCH("APK signing certificate differs from the associated certificate found in the signer's SigningCertificateLineage."),
    V3_INCONSISTENT_SDK_VERSIONS("APK Signature Scheme v3 signers supported min/max SDK versions are not continuous."),
    V3_MISSING_SDK_VERSIONS("APK Signature Scheme v3 signers supported min/max SDK versions do not cover the entire desired range.  Found min:  %1$s max %2$s"),
    V3_INCONSISTENT_LINEAGES("SigningCertificateLineages targeting different platform versions using APK Signature Scheme v3 are not all a part of the same overall lineage."),
    V31_BLOCK_MISSING("The v3 signer indicates key rotation should be supported starting from SDK version %1$s, but a v3.1 block was not found"),
    V31_ROTATION_MIN_SDK_MISMATCH("The v3 signer indicates key rotation should be supported starting from SDK version %1$s, but the v3.1 block targets %2$s for rotation"),
    V31_ROTATION_MIN_SDK_ATTR_MISSING("APK supports key rotation starting from SDK version %1$s, but the v3 signer does not contain the attribute to detect if this signature is stripped"),
    V31_BLOCK_FOUND_WITHOUT_V3_BLOCK("The APK contains a v3.1 signing block without a v3.0 base block"),
    V31_ROTATION_TARGETS_DEV_RELEASE_ATTR_ON_V3_SIGNER("The rotation-targets-dev-release attribute is only supported on v3.1 signers; this attribute will be ignored by the platform in a v3.0 signer"),
    /* JADX INFO: Fake field, exist only in values array */
    V4_SIG_VERSION_NOT_CURRENT("APK Signing Block contains unknown entry: ID %1$#x"),
    /* JADX INFO: Fake field, exist only in values array */
    V4_SIG_APK_ROOT_DID_NOT_VERIFY("V4 signature has malformed signer block"),
    /* JADX INFO: Fake field, exist only in values array */
    V4_SIG_VERSION_NOT_CURRENT("V4 signature has unknown signing algorithm: %1$#x"),
    /* JADX INFO: Fake field, exist only in values array */
    V4_SIG_APK_ROOT_DID_NOT_VERIFY("V4 signature has no signature found"),
    /* JADX INFO: Fake field, exist only in values array */
    V4_SIG_VERSION_NOT_CURRENT("V4 signature has no supported signature"),
    /* JADX INFO: Fake field, exist only in values array */
    V4_SIG_APK_ROOT_DID_NOT_VERIFY("%1$s signature over signed-data did not verify"),
    /* JADX INFO: Fake field, exist only in values array */
    V4_SIG_VERIFY_EXCEPTION("Failed to verify %1$s signature: %2$s"),
    /* JADX INFO: Fake field, exist only in values array */
    V4_SIG_APK_ROOT_DID_NOT_VERIFY("Malformed public key: %1$s"),
    /* JADX INFO: Fake field, exist only in values array */
    V4_SIG_VERSION_NOT_CURRENT("V4 signature has malformed certificate"),
    /* JADX INFO: Fake field, exist only in values array */
    V4_SIG_APK_ROOT_DID_NOT_VERIFY("V4 signature has no certificate"),
    /* JADX INFO: Fake field, exist only in values array */
    V4_SIG_VERSION_NOT_CURRENT("V4 signature has mismatched certificate and signature: <%1$s> vs <%2$s>"),
    /* JADX INFO: Fake field, exist only in values array */
    V4_SIG_APK_ROOT_DID_NOT_VERIFY("V4 signature's hash tree root (content digest) did not verity"),
    /* JADX INFO: Fake field, exist only in values array */
    V4_SIG_VERSION_NOT_CURRENT("V4 signature's hash tree did not verity"),
    V4_SIG_MULTIPLE_SIGNERS("V4 signature only supports one signer"),
    V41_SIG_NEEDS_TWO_SIGNERS("V4.1 signature requires two signers"),
    V4_SIG_V2_V3_SIGNERS_MISMATCH("V4 signature and V2/V3 signature have mismatched certificates"),
    V4_SIG_V2_V3_DIGESTS_MISMATCH("V4 signature and V%1$d signature have mismatched digests, V%1$d digest: %2$s, V4 digest: %3$s"),
    V4_SIG_UNEXPECTED_DIGESTS("V4 signature does not have the expected number of digests, found %1$d"),
    /* JADX INFO: Fake field, exist only in values array */
    V4_SIG_VERSION_NOT_CURRENT("V4 signature format version %1$d is different from the tool's current version %2$d"),
    SOURCE_STAMP_CERT_DIGEST_AND_SIG_BLOCK_MISSING("Neither the source stamp certificate digest file nor the signature block are present in the APK"),
    SOURCE_STAMP_SIG_MISSING("No SourceStamp signature"),
    SOURCE_STAMP_MALFORMED_CERTIFICATE("Malformed certificate: %1$s"),
    SOURCE_STAMP_MALFORMED_SIGNATURE("Malformed SourceStamp signature"),
    SOURCE_STAMP_UNKNOWN_SIG_ALGORITHM("Unknown signature algorithm: %1$#x"),
    SOURCE_STAMP_VERIFY_EXCEPTION("Failed to verify %1$s signature: %2$s"),
    SOURCE_STAMP_DID_NOT_VERIFY("%1$s signature over signed-data did not verify"),
    SOURCE_STAMP_NO_SIGNATURE("No signature"),
    SOURCE_STAMP_NO_SUPPORTED_SIGNATURE("Signature(s) {%1$s} not supported: %2$s"),
    SOURCE_STAMP_CERTIFICATE_MISMATCH_BETWEEN_SIGNATURE_BLOCK_AND_APK("Certificate mismatch between SourceStamp block in APK signing block and SourceStamp file in APK: <%1$s> vs <%2$s>"),
    SOURCE_STAMP_SIGNATURE_BLOCK_WITHOUT_CERT_DIGEST("A source stamp signature block was found without a corresponding certificate digest in the APK"),
    SOURCE_STAMP_EXPECTED_DIGEST_MISMATCH("The source stamp certificate digest in the APK, %1$s, does not match the expected digest, %2$s"),
    SOURCE_STAMP_MALFORMED_ATTRIBUTE("Malformed stamp attribute #%1$d"),
    SOURCE_STAMP_UNKNOWN_ATTRIBUTE("Unknown stamp attribute: ID %1$#x"),
    SOURCE_STAMP_MALFORMED_LINEAGE("Failed to parse the SigningCertificateLineage structure in the source stamp attributes section."),
    SOURCE_STAMP_POR_CERT_MISMATCH("APK signing certificate differs from the associated certificate found in the signer's SigningCertificateLineage."),
    SOURCE_STAMP_POR_DID_NOT_VERIFY("Source stamp SigningCertificateLineage attribute contains a proof-of-rotation record with signature(s) that did not verify."),
    SOURCE_STAMP_INVALID_TIMESTAMP("The source stamp timestamp attribute has an invalid value: %1$d"),
    SOURCE_STAMP_SIGNATURE_SCHEME_NOT_AVAILABLE("No digests are available in the source stamp for signature scheme: %1$d"),
    MALFORMED_APK("Malformed APK; the following exception was caught when attempting to parse the APK: %1$s"),
    UNEXPECTED_EXCEPTION("An unexpected exception was caught when verifying the signature: %1$s");


    /* renamed from: a, reason: collision with root package name */
    public final String f1246a;

    e(String str) {
        this.f1246a = str;
    }
}
